adaptlearning/adapt-contrib-vanilla

- less/block.less
- less/variables.less
During the course styling I've found that moving the padding of `.block-inner` to `variables.less` is more convenient.
> Externalised padding for .block-inner

- less/buttons.less
Fixes issue where border colours are defined in the vanilla theme.less but doesn't update the button borders for hover or disabled states for components.
> Missing border colours for button states

- less/responsive.less
At the snap-points between mobile and tablet, tablet and desktop the scrollbar appears due to a slight overstretch of the content under the scrollbar. The fix effectively hides this overflow so that the bottom (x-axis) scrollbar never appears.
> Fix for x axis overflow under scrollbar

- less/paddings.less
- less/src/adapt-defaults.less
- less/src/buttons.less
- less/src/drawer.less
- less/src/notify.less
- ABU-801, ABU-805, ABU-816 should all be fixed by the introduction of left / right padding onto the buttons class (paddings.less, adapt-defaults.less, buttons.less)
- Added transition effect to the drawer close icon and drawer items
- Amended hover state code to include no-touch class
- Added transition effect to the notify close icon
> ABU-801, ABU-805, ABU-816 Button padding, notify and drawer fixes

- less/src/gmcq.less
this fix hides the checkboxes of the gmcq without affecting the tab order
> hide checkboxes

- less/src/gmcq.less
removed duplicate styles.
ie8 does not apply opacity 0 to input elements, filter: alpha(opacity=0) added to fix this.
> hide checkbox on ie8 and cleanup

- less/src/drawer.less
Set the font size of the drawer description to the same as the body.
Text was being overwritten by the <a> to <button> change.
> Drawer Font Size Amend

- templates/notify.hbs
Accidentally removed a base class from the wrong button tag in an earlier commit
> Added base class

- templates/partials/component.hbs
Surrounded component title, body, and instruction elements in a wrapper div + inner.
Added {{_component}} to wrapper divs to allow for specific component styling.
Un-themed divs by default, implemented to give course authors an easier time if they'd like to give component headings a background.
https://github.com/adaptlearning/adapt_framework/issues/965
> Wrapped component.hbs with div tags

- less/src/navigation.less
Aligns the navigation bar centrally over the content in IE8
Fixes this bug https://github.com/adaptlearning/adapt_framework/issues/1579
> Bug fix, IE8 nav central alignment

- less/colors.less
- less/src/boxmenu.less
- less/src/navigation.less
- less/src/page-level-progress.less
[#2083](https://github.com/adaptlearning/adapt_framework/issues/2083)
* Made progress bars uniform in colour and size for dark and light backgrounds
* Added styling for new plp progress bars
* Added inner border to make bars easier to read
* Unified styling under new class name
[plp#107](https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/pull/107)
List of outstanding PRs: https://github.com/adaptlearning/adapt_framework/issues/2206.
> accessibility: issue/#2083 updated plp styling for completion indicators

- less/src/component.less
- less/src/theme-extras.less
blockquote is a button that is used in CKEditor (the text editor used in the AT) so it makes sense to add support for it in vanilla.
Also fixed indentations and spacing before braces
> Support for blockquote

- less/core/adapt-defaults.less
- less/core/navigation.less
- less/core/wrapper.less
[#2308](https://github.com/adaptlearning/adapt_framework/issues/2308)
* Removed unnecessary navigation styling
* Removed unneeded responsive-layout styling
* Left mixins for compatibility
Please check if this is breaking for your current themes.
Please test in conjunction with framework pr [#2309](https://github.com/adaptlearning/adapt_framework/issues/2309)
Test source:
[2308.zip](https://github.com/adaptlearning/adapt_framework/files/2698757/2308.zip)
> issue/2308: fixed theme responsive-layout styling

- less/project/theme-extras.less
fixes https://github.com/adaptlearning/adapt_framework/issues/2671
* Added block class `reverse-desktop-order` to easily reverse component visual order
> Class to reverse visual layout but retain dom order

- less/project/theme-extras.less
Issue https://github.com/adaptlearning/adapt_framework/issues/2676
* Updated `.reverse-desktop-order` class to use new component padding variable
> Updated .reverse-desktop-order with new component padding variable

- less/plugins/adapt-contrib-media/media.less
- less/plugins/adapt-contrib-media/mep.less
Resolves https://github.com/adaptlearning/adapt_framework/issues/2689
* Added a new file, mep.less, that overrides the standard mejs player controls styling by:
* Converting px to rems
* Introducing variables to change the main colour of the player bar, the icons within the player bar, and the time rail
* Converted player controls from images to icons to allow for bespoke icons to be added with ease
This PR is dependant on a Framework PR which includes the new media player icons: https://github.com/adaptlearning/adapt_framework/pull/2691
> Added mejs player override file

- less/plugins/adapt-contrib-boxmenu/boxMenuGroup.less
Related to feature request in this issue: https://github.com/adaptlearning/adapt_framework/issues/2702
* Adds vanilla theme styling to box menu group sections
> Added boxMenu group support

- less/plugins/adapt-contrib-pageLevelProgress/pageLevelProgressIndicator.less
Resolves https://github.com/adaptlearning/adapt_framework/issues/2523
* Improved specificity of pageLevelProgress title `display: inline-block;`
* Small clean up of nesting and comments
> Better pagelevelprogress display inline specificity

- example.json
- less/plugins/adapt-contrib-media/mep.less
Resolves https://github.com/adaptlearning/adapt_framework/issues/2695 and https://github.com/adaptlearning/adapt_framework/issues/2696
* Converted media play image to icon so it's easier to customise and scales better
* Added a custom class `invert-play-icon` that swaps the colour of the icon from white to black
* Updated example.json with custom class
> Converted media play image to icon

- less/core/component.less
- less/core/notify.less
Related issue: https://github.com/adaptlearning/adapt_framework/issues/2865
* Rewrote single column padding to be more specific
* Converted max-width specific media queries to min-width to sync js responsive trigger points
> Updated max-width media queries

- less/plugins/adapt-contrib-pageLevelProgress/pageLevelProgressIndicator.less
Related issue: https://github.com/adaptlearning/adapt_framework/issues/2912
* Removed plp specificity 
* Moved *-title-inner CSS to core
> Removed plp specificity for *-title-inner

- README.md
- properties.schema
fixes https://github.com/adaptlearning/adapt_framework/issues/3001
> add missing end quotes

- less/_defaults/_animations.less
Resolves https://github.com/adaptlearning/adapt_framework/issues/3056
* Override visibility transition by defining it explicitly in the onScreen animation CSS
> a11y visibility fix

- bower.json
- schema/article.schema.json
- schema/block.schema.json
- schema/contentobject.schema.json
- schema/theme.schema.json
Part of https://github.com/adaptlearning/adapt_framework/issues/2704.
> Add support for authoring tool 1

- less/core/attribution.less
Resolves https://github.com/adaptlearning/adapt-contrib-vanilla/issues/332
* Add `display: flex;` to `.gmcq__attribution` element to resolve visual display error 
Dependency:
https://github.com/adaptlearning/adapt-contrib-core/pull/133
https://github.com/adaptlearning/adapt-contrib-gmcq/pull/150
> GMCQ attribution fix

- less/_defaults/_colors.less
- less/plugins/adapt-contrib-resources/resources.less
I propose adding an underline to the selected tab.  The underline color can be set with a new color variable, @drawer-item-selected-underline, which defaults to @drawer-item-inverted.
Resolves #337
> #337 Add selected underline to filter tab

- example.json
- js/themeBlockView.js
- less/core/block.less
- less/project/theme-extras.less
- properties.schema
- schema/block.schema.json
Fixes: https://github.com/adaptlearning/adapt-contrib-vanilla/issues/353
* Consolidates the vertical alignment of components within a block into a json property that applies alignment classes on the block depending on property value
> Update: component vertical alignment property (fixes #353)

- less/core/attribution.less
Fixes: #352 
* Adds `display: block;` to image parent container when attribution is present. Issue caused by `<span>` have an inline display property
> Fix: Firefox attribution fix (fixes #352)

- example.json
Fixes: #367 
* Removed block alignment custom classes from example.json
> Docs: Removed block alignment custom classes (fixes #367)

- less/_defaults/_colors.less
- less/core/global.less
Fixes #349 
* Adds new body background color variable. Potentially breaking as this variable defaults to white.
1. In less/_defaults/_colors.less, change `@body-background-color` to something other than white.
> New: Add @body-background-color and apply to body element (fixes #349)

- example.json
Fixes: #365 
* Removed accordion and hotgraphic item image alignment custom classes from example.json
> Docs: Removed accordion / hotgraphic item image classes (fixes #365)

- README.md
- example.json
- js/theme.js
- js/themeComponentView.js
- js/themePageView.js
- js/themeView.js
- less/core/global.less
- properties.schema
- schema/article.schema.json
- schema/block.schema.json
- schema/component.schema.json
- schema/contentobject.schema.json
Fixes: #362 
* Added new text alignment property to page header, article, block, and component. Allows users to align title, body, or instruction elements to the left, center, or right.
> New: Text alignment update (fixes #362)

- less/project/theme-extras.less
Fixes: #372 
* Add missing default `black` value for `header-color` mixin
> Fix: Added missing header-color default (fixes: #372)

- README.md
- example.json
Fixes: #345 
* Updates to readme and example.json files 
* Moved json property explanations from readme and example.json to the [wiki](https://github.com/adaptlearning/adapt-contrib-vanilla/wiki/JSON-Config-and-Authoring-Tool-Options)
* Moved onScreen animation information from example.json to the [wiki](https://github.com/adaptlearning/adapt-contrib-vanilla/wiki/onScreen-Animation)
* Moved custom classes breakdown from example.json to the [wiki](https://github.com/adaptlearning/adapt-contrib-vanilla/wiki/Custom-Classes)
> Docs: Updated readMe and example.json (fixes #345)

- less/_defaults/_spacing-config.less
Fix: values of menu variables are inconsistent with similar elements
fixes #387
* @menu-body-margin changed from '0' to '1rem'
* @menu-instruction-margin changed from '0' to '1rem'
> update margins on menu-body and menu-instruction

- example.json
- js/themeBlockView.js
- less/core/block.less
- properties.schema
- schema/block.schema.json
Fixes #393
* Add new classes for `align-horz-center` and `align-horz-right`
* Add new block schema property for `_componentHorizontalAlignment` with the options of `left`, `center`, or `right`
Once approved and merged, this will need added to the Vanilla theme wiki.
> New: Add block horizontal alignment option (fixes #393)

- example.json
- js/theme.js
- properties.schema
- schema/course.schema.json
fixes https://github.com/adaptlearning/adapt-contrib-core/issues/306
* Added favicon support
Source url: https://www.adaptlearning.org/wp-content/uploads/2018/02/cropped-nav_logo_gold-192x192.png
Zip: [cropped-nav_logo_gold-192x192.zip](https://github.com/adaptlearning/adapt-contrib-vanilla/files/10863945/cropped-nav_logo_gold-192x192.zip)
* https://en.wikipedia.org/wiki/Favicon
* https://developer.mozilla.org/en-US/docs/Glossary/Favicon
* https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel#icon
* https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html#//apple_ref/doc/uid/TP40002051-CH3-SW4
> New: Added favicon support (fixes #306)

- less/plugins/adapt-contrib-narrative/narrative.less
Fixes #398 
* Removes hover states from progress indicators
https://github.com/adaptlearning/adapt-contrib-narrative/pull/250
> #398 Remove hover states from progress indicators

- less/plugins/adapt-contrib-glossary/glossary.less
Fixes https://github.com/adaptlearning/adapt-contrib-glossary/pull/69
Replace `.glossary__textbox-container` `margin` with `padding` to prevent search box shifting up when scrolled (see screenshots of issue).
When scrolled:
> Replace glossary search textbox margin with padding

- less/core/block.less
Fixes #403 
* `align-vert-center` class: Adds `min-height: inherit` to `.block__inner` and `.component__container`. This ensures components are vertically centered when using a minimum height on a block. 
Add the following config to a block that contains "short" component(s) like a Text component with minimal text:
```
"_vanilla": {
"_minimumHeights": {
"_large": 600,
"_medium": 600,
"_small": 200
},
"_componentVerticalAlignment": "center"
}
```
The result should be that the component inside the block is vertically centered.
> Fix: Make align-vert-center work with block min-heights (fixes #403)

- less/plugins/adapt-contrib-textInput/textinput.less
Fixes: #420 
* Added margin bottom to the textinput item, in a similar fashion to the gaps between accordion / mcq items
> Fix: Added textinput item bottom margin (fixes #420)

- less/_defaults/_font-config.less
- less/core/nav.less
Fixes #414 
* Adds new variable `@nav-btn-label-size` for the nav button label font size.
1. Switch core to `issue/338`
2. In course.json, enable nav labels with:
```
"_navigation": {
"_showLabel": true
},
```
3. Adjust `@nav-btn-label-size` in your theme and see it reflected in the nav button label text.
* Core: https://github.com/adaptlearning/adapt-contrib-core/pull/339
> Fix: Add font size variable for nav button label (fixes #414)

- less/_defaults/_colors.less
- less/core/loading.less
- less/core/shadow.less
Fix #424 
* Adds `@shadow-opacity` Less variable to control the opacity of the shadow overlay. This will be visible behind Notify popups and on the loading screen.
> Fix: Add @shadow-opacity variable (fixes #424)

- less/core/drawer.less
In [drawer.less](https://github.com/adaptlearning/adapt-contrib-vanilla/blob/aac3a2bdade9398bc9cf353dd40b64f5235096dd/less/core/drawer.less#L2), `.drawer` has a `background-color` defined but no `color`. Instead the `color` is inherited from `body`. 
I'd expect `.drawer` to use `color: @drawer-inverted`. Typically all Adapt elements use the named variable for `background-color` and the invert for `color`. For example:
```
.notify__popup {
background-color: @notify;
color: @notify-inverted;
}
```
Fixes #433
> Fix: set .drawer color (fixes #433)

- less/_defaults/_colors.less
- less/plugins/adapt-contrib-boxmenu/boxMenu.less
- properties.schema
- schema/theme.schema.json
Fixes #402 
* Adds new color variables for the menu header: `@menu-header-background-color`, `@menu-header-title-color`, `@menu-header-body-color`, and `@menu-header-instruction-color`
* Updates schemas
> Fix: Add new menu header color variables (fixes #402)

- less/_defaults/_spacing-containers.less
Added some notes to @navigation-height variable in theme to avoid confusion as this has now been deprecated in favour of an adapt css variable
> @navigation-height deprecated, added notes to avoid confusion

- less/_defaults/_font-config.less
Update instruction styling to 'normal' and weight to 'bold'. Update variables in menu & page header
Fixes: #395
> Fix: Convert the default instruction text styling from italics to bold

- schema/article.schema.json
> Fix: missing schema object name in article.schema.json

- less/core/notify.less
- less/core/notifyPush.less
- less/plugins/adapt-contrib-hotgraphic/hotgraphicPopup.less
- less/plugins/adapt-contrib-tutor/tutor.less
Fixes https://github.com/adaptlearning/adapt-contrib-vanilla/issues/443
The default style for Notify icon buttons is consistent across all plugins however the styles are duplicated across the various plugin LESS files.
Vanilla instances include:
- Notify popup and Notify push
- Hotgraphic popup
- Tutor popup
This PR wraps the existing icon button styles within a mixin and applies the mixin in the various plugin LESS files to replace duplicated code.
As the mixin is specific to Notify, the mixin remains in notify.less.
> Update: replace notify button icon duplicate styles with mixin (fixes #443)

- less/plugins/adapt-contrib-hotgraphic/hotgraphic.less
Fix #453 
* Remove background color on Hot Graphic pins when using pin images
See #453
> Fix: Remove background color on Hot Graphic pins when using pin images (fixes #453)

- less/plugins/adapt-contrib-hotgraphic/hotgraphic.less
Fixes https://github.com/adaptlearning/adapt-contrib-hotgraphic/issues/282
With the current implementation (PR [#281](https://github.com/adaptlearning/adapt-contrib-hotgraphic/pull/281)), the visited state pin displays larger than the unvisited number. The visited state inherits from `@icon-size` (`1.5rem`) whereas the number pin inherits from `@body-size` (`1rem`).
In this PR, `.hotgraphic__pin-number` inherits the icon styles for consistent pin number and visited state. See screenshot below.
Set `_useNumberedPins: true` for Hotgraphic and select the pins. Set `"_isNarrativeOnMobile": false`, to review PR on mobile.
> Update: Hotgraphic pin number inherits from the icon styles (fixes #282)

- less/plugins/adapt-contrib-narrative/narrative.less
Fix #450
When using the new mobile stacked layout:
* Adds spacing between Narrative items
* Adds spacing between Narrative item graphic and title
Are there better variables to use here? Or should we create new variables? My goal was to create enough spacing between items to clearly delineate each one.
```
&__widget.is-stacked &__content-item {
margin-bottom: (@item-margin * 4);
}
&__widget.is-stacked &__content-image {
margin-bottom: @item-title-margin;
}
```
Requires Narrative PR:
https://github.com/adaptlearning/adapt-contrib-narrative/pull/270
> Fix: Add margins for mobile stacked layout (fixes #450)

- properties.schema
- schema/article.schema.json
- schema/block.schema.json
- schema/contentobject.schema.json
Fix #456 
* Adds schema default values for Background image styles
1. Upload plugin to an AAT instance
2. Verify that there are default values for Repeat, Size and Position under Background image styles
> Fix: Add schema default values for background image styles (fixes #456)

- less/project/theme-common.less
Fix #460 
* Adds a white bg-color-mixin() to the out-of-the-box background color mixins
1. Add `bg-color white` to a block, component, etc.
> Fix: Add 'bg-color white' mixin (fixes #460)

- js/themePageView.js
- js/themeView.js
Fixes #462
* Exit early from `setHeaderBackgroundImage()` and `setHeaderBackgroundStyles()` if `this.$headerBackground` has not been set
* Exit early from `setBackgroundImage()` and `setBackgroundStyles()` if `this.$background` has not been set
* Fix deprecated `Adapt.device` references
> Fix: background and headerBackground undefined variable errors (fixes #462)

- less/plugins/adapt-contrib-boxmenu/boxMenuItem.less
Fixes https://github.com/adaptlearning/adapt-contrib-vanilla/issues/466 and https://github.com/adaptlearning/adapt-contrib-vanilla/issues/465
Currently, the height of menu items is based on the amount of text content which leads to inconsistent item heights.
This PR uses `display: flex` to display all items at equal height with no constraints on the content. Please see below for screenshots of how this looks in different use cases.
**Standard display:**
**Items using [column layout](https://github.com/adaptlearning/adapt-contrib-vanilla/blob/master/less/project/columns.less):**
**Items without image:**
I've also included #465 in this PR. The `margin-bottom` attached to the `.boxmenu-item__button-container` creates inconsistent spacing around the item (1rem top/left/right and 2rem bottom). …
> Update: use display flex to set equal menu item heights (fixes #466)

- properties.schema
- schema/theme.schema.json
Fixes https://github.com/adaptlearning/adapt-contrib-vanilla/issues/464
The default Vanilla colours are already applied via the CSS. Having schema defaults is another maintenance task when updating the colour variables - both maintaining Vanilla and creating bespoke themes.
> Update: remove default color hex codes from schemas (fixes #464)

- less/_defaults/_colors.less
Grey is widely recognised, and used in Adapt for disabled states so changing the visited colours to differentiate between the two. Variables replaced with a percentage of `@item-color` for consistency with other component states.
Fixes https://github.com/adaptlearning/adapt-contrib-vanilla/issues/470
> Update: Update visited color variables (fixes #470)

- less/_defaults/_spacing-config.less
- less/core/nav.less
Fixes: https://github.com/adaptlearning/adapt-contrib-vanilla/issues/472
* Introduced spacing to navigation buttons and navigation inner elements to emphasise that the buttons are clickable items.
> Update: Nav styling amends (fixes #472)

- less/_defaults/_spacing-config.less
Fixes: #476 
* Sets the `@nav-btn-*` variables to 0 so they have no visual impact on the builds but are there to be used if required
> Fix: Neutralised `nav-btn-*` variables (fixes #476)

- less/core/notify.less
Prevent generic `.btn-text `style overriding `.notify__btn` hover state by applying the same `:not` logic used in [less/core/buttons.less](https://github.com/adaptlearning/adapt-contrib-vanilla/blob/cb5fc98607b042487566bab99daf4c784f5f2afd/less/core/button.less#L26). Hover states should exclude locked and disabled states anyway.
Fixes https://github.com/adaptlearning/adapt-contrib-vanilla/issues/482
> Fix: prevent notify btn hover style override (fixes #482)

- less/core/drawerItem.less
Instead of applying `margin-bottom` to `.drawer__item-title` directly, apply `margin-top` to `.drawer__item-body` when needed.
Most Drawer plugin items only include a title. It's a minor issue but the addition of margin makes the title display off-center vertically.
Fixes https://github.com/adaptlearning/adapt-contrib-vanilla/issues/486
**Test PR**
In your course, go to PageLevelProgress and inspect `.drawer__item-title`. No margin should be applied. Same goes for Glossary or LanguagePicker.
Go to Drawer Resources and inspect `.drawer__item-title`. Margin should be applied to the top of `.drawer__item-body`, creating space between title and body.
> Only set .drawer__item-title margin if followed by .drawer__item-body

- less/core/drawerItem.less
- less/plugins/adapt-contrib-pageLevelProgress/pageLevelProgressIndicator.less
Relates to Core issue to [allow for locked and inactive disabled buttons to be visually different](https://github.com/adaptlearning/adapt-contrib-core/issues/485).
`.is-locked` - applies to buttons that are temporarily disabled due to step locked content.
`.is-disabled` - applies to buttons with functionality not available.
Drawer item locked state inherits from disabled state by default so there will be no visual changes. By introducing `.is-locked` class, this gives the flexibility of setting locked styling that can differ from the standard disabled styling.
> New: Add drawer item locked state 

- less/plugins/adapt-contrib-slider/slider.less
Fixes https://github.com/adaptlearning/adapt-contrib-vanilla/issues/484
* Remove legacy `z-index` properties from `.slider__number-selection` and `.slider__number-model-answer`.
[//]: # (List appropriate steps for testing if needed)
1. Enable Tutor `"_type": "overlay"` in a course, as per [example.json](https://github.com/adaptlearning/adapt-contrib-tutor/blob/ae525c06dfb0ca97e4a7bf96fb9a42ace93db3b0/example.json#L3).
2. Navigate to a Slider within your course and submit. 
3. Toggle _"Show correct answer"_ / _"show your answer"_ buttons to see both instances when feedback is displayed.
Tested on Mac Safari, Chrome, FF, iPhone and Chrome on Android. Please test on Windows.
> Fix: remove legacy z-index from slider number selection / model answer (fixes #484)

- less/project/theme-common.less
Fix #492 
* Utilize the `.size-small` html class to determine when `.hide-on-mobile` applies
See #492
> Fix: Utilize .size-small class for .hide-on-mobile class (fixes #492)

- less/_defaults/_spacing-containers.less
- less/core/page.less
Fixes #493 
* Changes `@max-width` to 100%
* Removes `max-width: inherit` from the `.page` element
1. In your theme's CSS:
```
@body-background-color: #96D5E4;
.page {
background-color: @white;
}
```
2. Change `@max-width` variable to 90rem
Blue body background color is visible on the sides.
> Fix: Change @max-width to 100%, remove max-width: inherit from .page (fixes #493)

- less/_defaults/_spacing-config.less
- less/plugins/adapt-contrib-pageLevelProgress/pageLevelProgressIndicator.less
Fixes https://github.com/adaptlearning/adapt-contrib-vanilla/issues/498
`@progress-border-radius` variable added for ease of amending the look of the indicator. The default value has been set to 50px for consistency with the plugin value and prevent any visual change in existing courses.
PLP indicator as default, `@progress-border-radius: 50px`:
Remove rounded corners setting `@progress-border-radius: 0`:
> Update: Replace PLP hard coded border-radius with variable (fixes #498)

- less/plugins/adapt-contrib-matching/dropdown.less
Fixes https://github.com/adaptlearning/adapt-contrib-vanilla/issues/478
For instances where the dropdown overlaps other question items. The border colour is the same as the `.dropdown__btn `expanded, `@item-color-selected`, to associate the list of options to the dropdown button.
The current styling applies the selected styles to the first item before a selection has been made. As this shares the same styles, `@item-color-selected` as `.dropdown__btn` the first item looks unavailable or already selected. See screen shots below.
Current styling when list expanded (selection yet to be made):
This PR only applies selected styles when a dropdown item has been selected:
> Fix: Matching dropdown list style improvements (fixes #478)

- less/plugins/adapt-contrib-gmcq/gmcq.less
Fixes #513 
* Adds the [MCQ item hover effect](https://github.com/adaptlearning/adapt-contrib-vanilla/blob/1d90e97fbafc75a095a6291073d0c31b3fd659ec/less/plugins/adapt-contrib-mcq/mcq.less#L15) to GMCQ items
1. Hover over an GMCQ item
2. It should animate similar to MCQ items. In other words, the radio or checkbox should have a pulse animation.
> Fix: Add hover effect to GMCQ items to match MCQ items (fixes #513)

- less/plugins/adapt-contrib-narrative/narrative.less
- less/project/theme-blocks.less
- less/project/theme-common.less
Fixes https://github.com/adaptlearning/adapt-contrib-vanilla/issues/509
* Narrative progress indicator `color` and `border-color` styles added to support [Narrative PR: completion icon added to progress indicators](https://github.com/adaptlearning/adapt-contrib-narrative/pull/301).
* `background-color` values remain the same for backwards compatibility (pre PR iterations of the plugin where the `border` property isn't defined).
* `bg-color` mixin updated to include `color` and `border-color` styles. 
* `bg-color` mixin `transparent-dark` and `transparent-light` conditions added to ensure a [minimum contrast ratio of 3:1](https://www.w3.org/WAI/WCAG21/Techniques/general/G207#:~:text=The%20first%20test%20of%20the,it%20passes%20the%20success%20criterion.).
*  Legacy `block-color` mixin …
> New: expand on Narrative progress indicator state styles (fixes #509)

- less/_defaults/_colors.less
- less/plugins/adapt-contrib-boxmenu/boxMenu.less
- properties.schema
- schema/theme.schema.json
Fixes #515 
* Adds the `@menu-header-subtitle-color` variable to control the menu subtitle color
1. In _course.json_, add a `subtitle` property
```
"title": "Adapt v5",
"displayTitle": "Adapt Version 5",
"subtitle": "Subtitle lorem ipsum",
```
2. In your theme, change the `@menu-header-subtitle-color` value.
> Fix: Add menu subtitle color variable (fixes #515)

- less/_defaults/_spacing-containers.less
- less/plugins/adapt-contrib-boxmenu/boxMenuItem.less
Fix #506 
* Add `@menu-item-inner-padding-ver` and `@menu-item-inner-padding-horz` variables to control box menu item padding
> Fix: Add variables to control box menu item padding (fixes #506)

- less/project/columns.less
Fixes #504 
* Adds new margin start and margin end column classes (e.g. `margin-start-sm-2` and `margin-end-md-1`) for indenting components from the left or right.
Configure two single width components using the existing [column](https://github.com/adaptlearning/adapt-contrib-vanilla/wiki/Custom-Classes#columns) classes and the new margin classes. For example, in the same block:
**Single width Text component**
Add classes `col-md-5 margin-start-md-1`. This makes the component 5 columns wide with a 1 column margin from the left at the medium breakpoint and higher.
**Single width Graphic component**
Add classes `col-md-4 margin-end-md-1`.  This makes the component 4 columns wide with a 1 column margin from the right at the medium breakpoint and higher.
The result for the above would look …
> New: Add margin start and margin end column classes (fixes #504)

- less/plugins/adapt-contrib-boxmenu/boxMenuItem.less
Fixes https://github.com/adaptlearning/adapt-contrib-vanilla/issues/520
* Apply margin to `.boxmenu-item__details` instead of `.boxmenu-item__image-container`. No visual change to the menu item spacing, just the application. When no image exists, margin isn't applied.
Please test with both Boxmenu master branch and [issue/198](https://github.com/adaptlearning/adapt-contrib-boxMenu/tree/issue/198).
> Update: Boxmenu item graphic margin to support latest template amends (fixes #520)

- less/plugins/adapt-contrib-matching/dropdown.less
Fixes https://github.com/adaptlearning/adapt-contrib-vanilla/issues/525
Fixes https://github.com/adaptlearning/adapt-contrib-matching/issues/193
* Restore matching dropdown options focus/selected highlight for keyboard users.
* Issue introduced during previous PR (Fix 2): https://github.com/adaptlearning/adapt-contrib-vanilla/pull/507
- _Tab_ to a Matching component, select _Enter_ to expand the dropdown button.
- Use _up_ / _down_ arrows to navigate between the options. 
- Use _spacebar_ to select an option.
The option receiving focus should be highlighted.
The selected option should be highlighted.
> Fix: restore matching dropdown options focus/selected highlight (fixes #525)

- less/plugins/adapt-contrib-mcq/mcq.less
part of https://github.com/adaptlearning/adapt_framework/issues/3597
* Added support for _canShowCorrectness
> New: Added mcq support for _canShowCorrectness

- less/plugins/adapt-contrib-gmcq/gmcq.less
part of https://github.com/adaptlearning/adapt_framework/issues/3597
* Added support for _canShowCorrectness
* When "_canShowMarking": true and "_canShowCorrectness": false, position marking state over selection state for consistency with mcq
> New: Added gmcq support for _canShowCorrectness

- .github/pull_request_template.md
- less/_defaults/_colors.less
Fix #535 
* Removes AAT-related note in `_colors.less` as it is no longer needed:
> // Note: If customising a theme for the Authoring Tool please update the
> // corresponding default value for that variable in the properties.schema file.
> // This is to stop any amended variables below being overwritten by
> // the Theme Picker in the Authoring Tool.
* Fix typo in PR template
> Update: Remove AAT note (fix #535)

- less/plugins/adapt-contrib-hotgraphic/hotgraphic.less
Fix #537 
* Allows number to be shown when using pin images
* Show visited checkmark when using pin images
Test alongside https://github.com/adaptlearning/adapt-contrib-hotgraphic/pull/338
https://github.com/adaptlearning/adapt-contrib-hotgraphic/pull/338
> Update: Allow showing number and visited checkmark when using pin images (fix #537)

- less/core/drawer.less
- less/core/notify.less
- less/core/shadow.less
part of https://github.com/adaptlearning/adapt-contrib-core/issues/600
requires https://github.com/adaptlearning/adapt-contrib-core/pull/601
* Added default notify and drawer css animations
> Fix: Added notify and drawer default CSS animations

- less/project/theme-common.less
Fixes #539 
* Adds article to the `bg-color` mixin
1. Add a `bg-color` class to an article
2. Add `displayTitle`, `body`, and `instruction` values to the article
Text colors should be changed in the article header text
> Fix: Add article to bg-color mixin (fix #539)

- less/core/buttonQuestion.less
Fix #558 
* Adds end margin only when question is complete
* Needs this Core PR approved as well: https://github.com/adaptlearning/adapt-contrib-core/pull/683
> Fix: Add end margin only when question is complete (fix #558)
