- less/focus.less
Two separate rules were in conflict
> Made focus rule uniform

- less/buttons.less
> IE8 fix for buttons - fixes Issue #70

- templates/drawer.hbs
- templates/navigation.hbs
- templates/notify.hbs
- templates/notifyPush.hbs
To resolve: https://github.com/adaptlearning/adapt_framework/issues/541
> _globals.accessibility fix

- less/article.less
- less/block.less
- less/buttons.less
- less/component.less
- less/drawer.less
- less/fonts.less
- less/icons.less
- less/layout.less
- less/loading.less
- less/navigation.less
- less/notify.less
- less/page.less
- less/responsive.less
- less/shadow.less
- less/theme.less
- less/variables.less
Improvements to legibility of the CSS
Theme colour amends
> Refactored, reordered colours, colour amends

- less/variables.less
https://adaptlearning.atlassian.net/browse/ABU-533
Increased contrast for IE8 disabled state for matching dropdowns and general buttons.
> fix for disabled buttons

- less/src/narrative.less
Not sure if the padding or line hight should be separated out more into font and padding less files.
> Narrative styles to replace component

- less/src/component.less
- templates/partials/component.hbs
Component Title and Instruction Text updated to meet the AD:
- Removed .h4 from components template
- added Variables
> Components less

- less/src/accordion.less
Accordion styles to replace component
> new theme variables implemented

- less/src/textinput.less
Not much to change in this one. Left some of the classes for input and labels in so widths can be changed.
> Text input less file

- less/src/hotgraphic.less
variables implemented
image width changed to 100%
> variables implemented

- less/src/page-level-progress.less
- basic styling added to override extension with updated variables.
> navigation and drawer page level progress

- less/src/media.less
Do we need to add anything else? Would need some assets to change the play button.
> Update transcript less

- less/src/slider.less
Move scale line markers as per AD
> Move line markers below slider-scaler

- less/src/narrative.less
narrative content color variables implemented
> narrative content bg-color and color variables added

- example.json
- js/theme-block.js
- js/vanilla.js
- less/src/theme-extras.less
- block bg color configurable in json (as per brief).
- block min height configurable in the json (set for different device widths).
- divider block now a configurable option.
> Block config

- less/src/assessmentResults.less
Not sure if assessment results total should have generic padding applied
> Assessment results less

- less/src/buttons.less
To fix styling issue with transcript button on media which inherits from buttons
> Center button text

- less/src/theme-extras.less
Update .background-color-inverted class to include @font-color-inverted
Potentially could also be done as 
.component-title,
.component-body,
.component-instruction {
color: @font-color-inverted;
}
> Update .background-color-inverted class

- templates/page.hbs
https://adaptlearning.atlassian.net/browse/ABU-867
> Added aria-label to indicate end of page.

- less/src/slider.less
variable percentage lightened - https://github.com/adaptlearning/adapt-contrib-vanilla/issues/160
> fix issue #160

- less/src/hotgraphic.less
- less/src/icons.less
- Theme less updated to include hotgraphic component changes https://github.com/adaptlearning/adapt-contrib-hotgraphic/pull/110.
> Hotgraphic.less 

- templates/drawer.hbs
> a to button

- less/src/boxmenu.less
fixes theme issues due to converting a tag to button
> ABU-1068 theme fix

- templates/notify.hbs
Not needed and causes rendering errors
> Removed base class from button

- less/src/drawer.less
- templates/drawer.hbs
Make resources drawer tabbing cycle more logical
https://github.com/adaptlearning/adapt_framework/issues/895
> issue-895: drawer close button

- bower.json
- less/src/slider.less
theme updated to work with slider changes
> issue #937

- less/src/focus.less
https://github.com/adaptlearning/adapt_framework/issues/1230
has been raised as a concern more than once
> issue-1230: re-added default focus rectangle

- templates/drawer.hbs
- templates/navigation.hbs
- templates/notify.hbs
- templates/notifyPush.hbs
https://github.com/adaptlearning/adapt_framework/issues/1254
> Removed role=button

- less/src/navigation.less
- templates/navigation.hbs
Issue url: https://github.com/adaptlearning/adapt_framework/issues/1388
adding 'skip navigation' button to template
> Issue 1388

- templates/notify.hbs
Required to render 'data-adapt-id' as part of https://github.com/adaptlearning/adapt_framework/issues/1427.
> Adds the ability to render attributes as part of the Notify

- less/src/matching.less
Used styling from component less.
Removed styles that are not relevant for theming.
> select2 theme update 

- less/src/page-level-progress.less
This fixes the issue described at:
https://github.com/adaptlearning/adapt_framework/issues/1623
> issues/#1623: fixed rtl support for progress bar

- less/generic.less
issue: https://github.com/adaptlearning/adapt_framework/issues/1631
grunt compiler: https://github.com/adaptlearning/adapt_framework/blob/master/grunt/tasks/less.js#L28-L30
> issue/1631: plumb json into less _screenSize

- less/generic.less
https://github.com/adaptlearning/adapt_framework/issues/1631
I missed adding the units onto these variables.
> issue/1631: added units to screenSize

- less/src/page-level-progress.less
Incorrect hover state showing on mobile devices.
> fixes #1816

- less/src/icons.less
Part of https://github.com/adaptlearning/adapt_framework/issues/1805.
goes with https://github.com/adaptlearning/adapt_framework/pull/1827 removal of font files
> Remove old font references

- less/src/boxmenu.less
https://github.com/adaptlearning/adapt_framework/issues/1839
switched to using ``.boxmenu-menu`` instead of ``.menu``
> issue/1839: made boxmenu styling more specific

- less/src/navigation.less
[#2168](https://github.com/adaptlearning/adapt_framework/issues/2168)
* Override and utilize @navigation-height
[fwk#2169](https://github.com/adaptlearning/adapt_framework/pull/2169)
> issue/#2168 Utilized @navigation-height

- less/generic.less
- less/src/focus.less
[#2137](https://github.com/adaptlearning/adapt_framework/issues/2137)
* Reverted to browser defaults
> accessibility: issue/#2137 reverted to browser default focus rectangle

- less/src/navigation.less
[#2273](https://github.com/adaptlearning/adapt_framework/issues/2273)
* Removed duplicate declaration
> issue/2273: removed duplicate declaration

- properties.schema
Issue: https://github.com/adaptlearning/adapt_framework/issues/2359
> Expose all colour variables to authoring tool editor (v3)

- properties.schema
Issue: https://github.com/adaptlearning/adapt_framework/issues/2359
> Expose all colour variables to authoring tool editor

- less/_defaults/_animations.less
- less/plugins/adapt-contrib-pageLevelProgress/pageLevelProgressIndicator.less
Resolves https://github.com/adaptlearning/adapt_framework/issues/2612
> Adds width animation to PLP indicator

- less/plugins/adapt-contrib-accordion/accordion.less
- less/plugins/adapt-contrib-boxmenu/boxMenuItem.less
- less/plugins/adapt-contrib-graphic/graphic.less
- less/plugins/adapt-contrib-hotgraphic/hotgraphicPopup.less
- less/plugins/adapt-contrib-narrative/narrative.less
https://github.com/adaptlearning/adapt_framework/issues/2615
> img zoom enable class added

- less/core/button.less
https://github.com/adaptlearning/adapt_framework/issues/2627
> Button marking fix

- less/plugins/adapt-contrib-languagePicker/languagePicker.less
Resolves https://github.com/adaptlearning/adapt_framework/issues/2631
> Added button margin

- less/core/button.less
Resolves https://github.com/adaptlearning/adapt_framework/issues/2633
> Added .is-locked support for .btn-text

- less/plugins/adapt-contrib-hotgraphic/hotgraphicPopup.less
https://github.com/adaptlearning/adapt_framework/issues/2636
> Toolbar no pagination fix

- less/core/notifyPush.less
Related issue: https://github.com/adaptlearning/adapt_framework/issues/2640
> Notify push reintroduction

- less/plugins/adapt-contrib-accordion/accordion.less
- less/plugins/adapt-contrib-media/media.less
- less/plugins/adapt-contrib-narrative/narrative.less
Related issue: adaptlearning/adapt_framework#2646
> hyperlink styling for component items

- less/plugins/adapt-contrib-boxmenu/boxMenuItem.less
[2658](https://github.com/adaptlearning/adapt_framework/issues/2658)
> Prevent hover style being applied to locked item

- less/plugins/adapt-contrib-gmcq/gmcq.less
- less/plugins/adapt-contrib-matching/dropdown.less
- less/plugins/adapt-contrib-mcq/mcq.less
- less/plugins/adapt-contrib-slider/slider.less
MCQ / GMCQ / Matching / Slider focus states added / updated
Issue: https://github.com/adaptlearning/adapt_framework/issues/2668
> Amended question focus states

- less/_defaults/_animations.less
Resolves https://github.com/adaptlearning/adapt_framework/issues/2675
Added `overflow: hidden;` to animation container.
Amended animation element to be direct child of container.
General tidy up and optimisation of `_animations.less` file.
> Fix for overflowing animation, _animations.less tidy up

- less/_defaults/_font-config.less
- less/_defaults/_font-mixins.less
- less/plugins/adapt-contrib-text/text.less
Resolves https://github.com/adaptlearning/adapt_framework/issues/2687
* Amends to reduce the font size of the title and body text so the pull quote styling can work for short, mid, and long quotes.
> Pull quote theme amends

- less/_defaults/_colors.less
- properties.schema
Resolves https://github.com/adaptlearning/adapt_framework/issues/2609
> Removed schema theme picker defaults

- assets/readme.txt
- fonts/readme.txt
- templates/readme.txt
Resolves: https://github.com/adaptlearning/adapt_framework/issues/2792
> Added assets, fonts, and template folders with readme docs

- less/project/theme-extras.less
Resolves https://github.com/adaptlearning/adapt_framework/issues/2690
Adds:
* Hide page header
* Align child components to bottom of parent block
* Reduce top and bottom block padding by half
* Double top and bottom block padding 
* Added alternate remove top and bottom padding class (so it follows CSS pattern of [property]-[direction])
> Added new custom classes to theme-extras

- README.md
- example.json
Resolves https://github.com/adaptlearning/adapt_framework/issues/2795
* Updated example.json file to list Adapt and Vanilla standard classes
* Updated readme to link through to additional standard classes in example.json
* Tweaked folder structure table to reflect additional assets / fonts / templates folders
> Added collection of custom Adapt classes + updated readme

- example.json
- less/project/theme-extras.less
resolves https://github.com/adaptlearning/adapt_framework/issues/2821
> resolves #2821

- bower.json
- less/plugins/adapt-contrib-narrative/narrative.less
Narrative visited item styling for desktop layout https://github.com/adaptlearning/adapt_framework/issues/2855
> #2855 Narrative item visited styling

- bower.json
- less/plugins/adapt-contrib-hotgraphic/hotgraphic.less
Supports https://github.com/adaptlearning/adapt-contrib-hotgraphic/pull/194
> Hotgraphic numbered pins styling

- properties.schema
Resolves https://github.com/adaptlearning/adapt_framework/issues/2686
* Improves AT Theme Config editor help text
> Improved theme config editor help text

- less/_defaults/_spacing-containers.less
Resolves https://github.com/adaptlearning/adapt_framework/issues/2911
* Added `@component-padding-hoz` variable
* Removed unnecessary 0 values
> Added component-padding-hoz variable

- js/theme.js
- js/themeArticleView.js
- js/themeBlockView.js
- js/themePageView.js
- js/themeView.js
* double-quotes > single
* remove unused Adapt imports
> code formatting

- less/plugins/adapt-contrib-boxmenu/boxMenuItem.less
Resolves https://github.com/adaptlearning/adapt_framework/issues/2929
* Adds colours to menu item button for locked and disabled states
> Added disabled and locked states to menuItem btn

- less/_defaults/_font-config.less
- less/_defaults/_font-mixins.less
Resolves https://github.com/adaptlearning/adapt_framework/issues/2701
* Adds new variables `*-mobile-percentage` to menu / page title and subtitle, article, block, component and notify
* Sets new variable value to `.75`
* Amends to aforementioned element font mixins
> Responsive titles

- less/plugins/adapt-contrib-pageLevelProgress/pageLevelProgressIndicator.less
resolves https://github.com/adaptlearning/adapt_framework/issues/2982
> drawer pagelevelprogress disabled styling

- README.md
- example.json
- js/themeView.js
- properties.schema
Resolves https://github.com/adaptlearning/adapt_framework/issues/2892
* Implement a function that allows classes to be added and removed responsively
> Responsive classes

- less/_defaults/_colors.less
- less/core/button.less
- less/core/drawer.less
- less/core/nav.less
- less/core/notify.less
- less/core/notifyPush.less
- less/plugins/adapt-contrib-hotgraphic/hotgraphic.less
- less/plugins/adapt-contrib-hotgraphic/hotgraphicPopup.less
- less/plugins/adapt-contrib-narrative/narrative.less
- properties.schema
Resolves https://github.com/adaptlearning/adapt_framework/issues/2685
* Adds a new series of variables for `btn-icon`, setting up a default icon button style
> btn-icon variables added

- example.json
- less/project/theme-extras.less
Resolves https://github.com/adaptlearning/adapt_framework/issues/3162
* Adds a new extend container class that increases the content container width from 900px to 1120px
> Added smaller extend container class

- example.json
Resolves https://github.com/adaptlearning/adapt_framework/issues/3160
* Adds custom narrative class to vanilla example.json
> Added narrative custom class to example.json

- example.json
- less/project/theme-extras.less
Resolves https://github.com/adaptlearning/adapt_framework/issues/3161
* Reduces specificity of background color mixin
> Reduced specificity of background color mixin

- example.json
- less/plugins/adapt-contrib-media/mep.less
resolves https://github.com/adaptlearning/adapt_framework/issues/3191
> option to offset media controls

- less/_defaults/_spacing-containers.less
- less/plugins/adapt-contrib-boxmenu/boxMenu.less
resolves https://github.com/adaptlearning/adapt_framework/issues/3192
> add space between Boxmenu header and menu items

- less/_defaults/_font-mixins.less
...for consistency with other bold text
https://github.com/adaptlearning/adapt_framework/issues/3193
> use variable to define b and strong font weight

- README.md
- bower.json
- package.json
- properties.schema
- schema/article.schema.json
- schema/block.schema.json
- schema/contentobject.schema.json
closes #301
Adds "100% 100%" to schemas, amends help in schemas, amends README.
> add option to background-image size

- less/plugins/adapt-contrib-accordion/accordion.less
Related to https://github.com/adaptlearning/adapt_framework/issues/3255
Related fix for accordion https://github.com/adaptlearning/adapt-contrib-accordion/pull/109
Potentially a breaking change
> Accordion item class naming fix

- less/plugins/adapt-contrib-mcq/mcq.less
Resolves https://github.com/adaptlearning/adapt-contrib-vanilla/issues/309
* Converted mcq naming so each item is treated as a block within BEM
> mcq bem naming amends

- less/plugins/adapt-contrib-matching/dropdown.less
- less/plugins/adapt-contrib-matching/matching.less
Resolves https://github.com/adaptlearning/adapt-contrib-vanilla/issues/311
* Converted matching naming so each item is treated as a block within BEM
> Matching BEM naming corrections

- less/plugins/adapt-contrib-gmcq/gmcq.less
Related to https://github.com/adaptlearning/adapt-contrib-vanilla/issues/307
Related GMCQ fix https://github.com/adaptlearning/adapt-contrib-gmcq/pull/141
Potentially a breaking change
> GMCQ BEM naming correction

- less/plugins/adapt-contrib-textInput/textinput.less
Resolves https://github.com/adaptlearning/adapt-contrib-vanilla/issues/313
* Related to textinput issue [107](https://github.com/adaptlearning/adapt-contrib-textInput/issues/107)
> TextInput inconsistent BEM naming

- less/core/global.less
Resolves https://github.com/adaptlearning/adapt-contrib-vanilla/issues/317
* Add support for icons to appear inline with text - can be title / body / instruction
> Inline icon support

- js/theme.js
fixes #319 
* Main singleton instance created on load
> issue/319 Fixed es6 conversion bug

- less/_defaults/_spacing-containers.less
- less/project/theme-extras.less
Resolves https://github.com/adaptlearning/adapt-contrib-vanilla/issues/316
* Adds component header background colour as an enhancement
> issue/316 Component header background

- less/_defaults/_spacing-containers.less
- less/core/component.less
- less/project/columns.less
Resolves https://github.com/adaptlearning/adapt-contrib-vanilla/issues/315
* Addition of component vertical padding variable
* Addition of vertical / horizontal component padding 
* Removal of prior responsive padding fixes
* Addition of negative horizontal margin to offset padding so blocks are 900px wide
> issue/315 Standardise component padding

- less/project/theme-extras.less
Resolves https://github.com/adaptlearning/adapt-contrib-vanilla/issues/323
* Adds hide classes for desktop / mobile (using medium breakpoint)
> Hide custom classes

- less/core/component.less
- less/project/columns.less
Resolves #326 
Moves padding styles from project/columns.less to core/component.less.
> move component padding styles

- less/_defaults/_animations.less
Resolves #325
Adds to the mixin a parameter that accepts a time value as a delay. The default is 1s. This provides more control of when the animation starts.
> add transition-delay to animation mixin

- less/plugins/adapt-contrib-hotgraphic/hotgraphic.less
Resolves #335 
Adds Hotgraphic styling for https://github.com/adaptlearning/adapt-contrib-hotgraphic/pull/233
> issue/335 Add Hotgraphic styling for visited icon

- js/theme.js
- js/themePageView.js
- js/themeView.js
- less/core/article.less
- less/core/block.less
- less/core/page.less
- less/plugins/adapt-contrib-boxmenu/boxMenu.less
fixes #342 
fixes https://github.com/cgkineo/adapt-visua11y/issues/38
* Moved background images into their own divs
* Modified styling to replicate the styling
test with https://github.com/adaptlearning/adapt-contrib-boxMenu/pull/119
> issue/38 Moved background images into their own divs

- README.md
Fixes: #360 
* Adds readme entry for _componentVerticalAlignment
> Fix: Updated readme (fixes #360)

- README.md
- bower.json
- example.json
- js/themeBlockView.js
- less/core/block.less
- less/project/theme-extras.less
- package.json
- properties.schema
- schema/block.schema.json
Fixes: #358
* Consolidates the blocks top and bottom padding into json properties that apply classes on the block depending on property value
> Breaking: block padding property (fixes #358)

- less/project/theme-extras.less
Fixes: #374 
* Added missing defaults for component header bg mixin
> Fix: Added missing defaults for comp header bg mixin (fixes: #374)

- less/_defaults/_spacing-containers.less
- less/project/columns.less
- less/project/theme-extras.less
- package.json
Fixes: #379 
* Added new variable `@max-content-width`, set to inherit `@device-width-large`
* Added new variable `@max-page-width`, set to inherit `@max-width`
* Changed `@max-width` to `@max-page-width`
Dependencies
* Core [pull 275](https://github.com/adaptlearning/adapt-contrib-core/pull/275)
* BoxMenu [pull 131](https://github.com/adaptlearning/adapt-contrib-boxMenu/pull/131)
* LanguagePicker [pull 76](https://github.com/adaptlearning/adapt-contrib-languagePicker/pull/76)
> Update: Control content max width via variable (fixes #379)

- less/plugins/adapt-contrib-gmcq/gmcq.less
- less/plugins/adapt-contrib-matching/dropdown.less
- less/plugins/adapt-contrib-mcq/mcq.less
- less/plugins/adapt-contrib-narrative/narrative.less
- less/plugins/adapt-contrib-slider/slider.less
Fixes: #376 
Fixes: #377
* Converted `:focus` to `:focus-visible`
* Changed display of strapline icon styling to improve focus rendering
> Update: Convert focus to focus-visible (fixes #376 #377)

- less/_defaults/_spacing-config.less
- less/plugins/adapt-contrib-boxmenu/boxMenuItem.less
[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)
[//]: # (Link the PR to the original issue)
* Adds menu lock indicator to solve for #389 
[//]: # (List appropriate steps for testing if needed)
1. Install this PR 
2. Also grab adapt-contrib-boxmenu update for styling: https://github.com/adaptlearning/adapt-contrib-boxMenu/pull/136
[//]: # (Mention any other dependencies)
You must also use the PR from adapt-contrib-boxmenu: https://github.com/adaptlearning/adapt-contrib-boxMenu/pull/136
> New: Adds locking icon to locked menu items (fixes: #389)

- js/theme.js
[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)
[//]: # (Link the PR to the original issue)
* Fixes #400
* Pointed out by @swashbuck. He also kindly supplied the fix.
[//]: # (List appropriate steps for testing if needed)
1. Pull down, remove theme fields from course.json, ensuring an error isn't thrown.
[//]: # (Mention any other dependencies)
> Fix: Defensive Check (fixes: #400)

- less/plugins/adapt-contrib-slider/slider.less
Fix: #407 
* Added native slider bar fill styling
* Ported native slider marking styling from plugin 
* https://github.com/adaptlearning/adapt-contrib-slider/pull/183
> Fix: Added slider fill and marking styling (fixes #407)

- schema/course.schema.json
[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)
[//]: # (Link the PR to the original issue)
Fixes #418 
* Remove the default `_vanilla._favicon._src` schema value
[//]: # (List appropriate steps for testing if needed)
1. Upload to v1 AAT
2. Attempt to save the project settings page
> Fix: Remove _favicon._src default schema value (fixes #418)

- less/project/columns.less
- package.json
fixes #428 
* Match columns to breakpoints
> Fix: Match columns to breakpoints

- example.json
- js/themePageView.js
- js/themeView.js
- less/_defaults/_spacing-containers.less
- properties.schema
- schema/article.schema.json
- schema/block.schema.json
- schema/contentobject.schema.json
Added xlarge to theme. 
Fixes #431
> Fix: Add missing xlarge to vanilla theme

- less/_defaults/_spacing-config.less
- less/plugins/adapt-contrib-boxmenu/boxMenuItem.less
Fixes: #436 
* Convert item and button borders from px to rem.
> Fix: convert item and button borders from px to rem (fixes #436)

- less/plugins/adapt-contrib-media/media.less
Fixes: #473 
* Add selected and visited (completed) styling to the media transcript button that mirrors the accordion item styling
> Update: Media transcript completion styling (fixes #473)

- less/core/button.less
- less/core/drawerItem.less
- less/core/notify.less
- less/core/notifyPush.less
- less/plugins/adapt-contrib-accordion/accordion.less
- less/plugins/adapt-contrib-glossary/glossary.less
- less/plugins/adapt-contrib-matching/dropdown.less
- less/plugins/adapt-contrib-mcq/mcq.less
- less/plugins/adapt-contrib-narrative/narrative.less
- less/plugins/adapt-contrib-textInput/textinput.less
- less/plugins/adapt-contrib-tutor/tutor.less
- less/project/theme-common.less
Fixes #480 
* Updated RTL styling to remove unnecessary declarations
> Update: Updated RTL styling (fixes #480)

- less/_defaults/_animations.less
- less/_defaults/_colors.less
- less/core/loading.less
- properties.schema
- schema/theme.schema.json
Fixes #500
* Fixes and refreshes the loading icon within Adapt
* Adds new loading colour variables
* Updated associated schemas
> Fix: Loading animation updated (fixes #500)

- less/_defaults/blend.less
Fixes: #502 
* Utilise the each list function to optimise the `blend.less` file
> Fix: Optimise `blend.less` (fixes #502)

- less/plugins/adapt-contrib-accordion/accordion.less
Fixes: #529 
* Added support for vertical accordion items
* Added support for accordion custom title icons
Requires accordion PR https://github.com/adaptlearning/adapt-contrib-accordion/pull/155
> New: Add support for vertical accordion items and custom title icons (fixes #529)

- schema/article.schema.json
- schema/block.schema.json
- schema/contentobject.schema.json
- schema/course.schema.json
[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)
[//]: # (Link the PR to the original issue)
#533 
* isObjectId removed from schema to allow external assets to be added (fixes #533)
>  Fix: isObjectId removed from schema to allow external assets to be added (fixes #533)

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/issue_template.md
Fixes https://github.com/adaptlearning/adapt-contrib-vanilla/issues/543
* Add new `issue_template.md` file with YAML frontmatter
* Add new `config.yml` file to disable blank template
> Chore: Add support for new issue experience (fixes #543)
